<a href="https://colab.research.google.com/github/hansanagayathmika2003-ctrl/Online-Learning-Engagement/blob/main/Online_Learning_Engagement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/class-dataset/online_learning_engagement_dataset.csv')

In [ ]:
df.head()

,student_id,age,gender,country,device_type,internet_speed_mbps,study_hours_weekly,login_frequency_weekly,avg_session_duration_min,video_watch_time_min,assignments_submitted,forum_posts,quiz_attempts,avg_quiz_score,attendance_rate,engagement_score,final_grade,dropout
0,1,24,Female,USA,Laptop,44.70,15.92,10,40.052752,294.099759,3,4,6,46.69,0.93,8.046499,22.447641,0
1,2,37,Female,Germany,Tablet,61.10,6.37,8,32.442671,400.397658,7,14,5,62.65,0.59,6.312988,39.749905,1
2,3,46,Female,Australia,Tablet,43.10,6.64,7,43.614509,190.239738,1,14,5,58.42,0.43,4.143199,31.061688,1
3,4,32,Male,India,Tablet,26.99,10.91,5,30.697263,370.451629,3,1,2,61.21,0.65,6.125258,41.300634,0
4,5,28,Male,India,Laptop,52.28,7.41,6,47.402999,151.341296,4,4,6,74.92,0.55,4.979706,39.148998,1

In [ ]:
df.shape

(50000, 18)

In [ ]:
df.columns

Index(['student_id', 'age', 'gender', 'country', 'device_type',
       'internet_speed_mbps', 'study_hours_weekly', 'login_frequency_weekly',
       'avg_session_duration_min', 'video_watch_time_min',
       'assignments_submitted', 'forum_posts', 'quiz_attempts',
       'avg_quiz_score', 'attendance_rate', 'engagement_score', 'final_grade',
       'dropout'],
      dtype='object')

In [ ]:
df.dtypes

student_id                    int64
age                           int64
gender                       object
country                      object
device_type                  object
internet_speed_mbps         float64
study_hours_weekly          float64
login_frequency_weekly        int64
avg_session_duration_min    float64
video_watch_time_min        float64
assignments_submitted         int64
forum_posts                   int64
quiz_attempts                 int64
avg_quiz_score              float64
attendance_rate             float64
engagement_score            float64
final_grade                 float64
dropout                       int64
dtype: object

In [ ]:
df.info

<bound method DataFrame.info of        student_id  age  gender    country device_type  internet_speed_mbps  \
0               1   24  Female        USA      Laptop                44.70
1               2   37  Female    Germany      Tablet                61.10
2               3   46  Female  Australia      Tablet                43.10
3               4   32    Male      India      Tablet                26.99
4               5   28    Male      India      Laptop                52.28
...           ...  ...     ...        ...         ...                  ...
49995       49996   41    Male     Canada      Laptop                72.05
49996       49997   41  Female        USA      Laptop                49.61
49997       49998   28    Male        USA      Mobile                65.99
49998       49999   19  Female  Australia      Mobile                44.48
49999       50000   36  Female    Germany      Tablet                41.16

       study_hours_weekly  login_frequency_weekly  avg_session_duration_min  \
0                   15.92                      10                 40.052752
1                    6.37                       8                 32.442671
2                    6.64                       7                 43.614509
3                   10.91                       5                 30.697263
4                    7.41                       6                 47.402999
...                   ...                     ...                       ...
49995               16.67                      11                 29.357895
49996               10.89                       5                 46.521225
49997               13.02                      11                 25.405865
49998               10.00                      10                 53.393459
49999                5.70                      13                 42.648018

       video_watch_time_min  assignments_submitted  forum_posts  \
0                294.099759                      3            4
1                400.397658                      7           14
2                190.239738                      1           14
3                370.451629                      3            1
4                151.341296                      4            4
...                     ...                    ...          ...
49995            317.570722                      4           13
49996            378.638038                      5            4
49997            358.872387                      3            7
49998            597.282683                      5            1
49999            310.477185                      0           10

       quiz_attempts  avg_quiz_score  attendance_rate  engagement_score  \
0                  6           46.69             0.93          8.046499
1                  5           62.65             0.59          6.312988
2                  5           58.42             0.43          4.143199
3                  2           61.21             0.65          6.125258
4                  6           74.92             0.55          4.979706
...              ...             ...              ...               ...
49995              1           49.05             0.47          7.588854
49996              1           64.51             0.73          6.360190
49997              1           97.90             0.60          6.500362
49998              6           73.26             0.55          8.186413
49999              6           80.46             0.95          4.462386

       final_grade  dropout
0        22.447641        0
1        39.749905        1
2        31.061688        1
3        41.300634        0
4        39.148998        1
...            ...      ...
49995    23.339360        1
49996    41.131751        0
49997    54.854903        0
49998    39.917221        1
49999    37.596538        0

[50000 rows x 18 columns]>

In [ ]:
df.isnull().sum()

student_id                  0
age                         0
gender                      0
country                     0
device_type                 0
internet_speed_mbps         0
study_hours_weekly          0
login_frequency_weekly      0
avg_session_duration_min    0
video_watch_time_min        0
assignments_submitted       0
forum_posts                 0
quiz_attempts               0
avg_quiz_score              0
attendance_rate             0
engagement_score            0
final_grade                 0
dropout                     0
dtype: int64

In [ ]:
df.describe()

,student_id,age,internet_speed_mbps,study_hours_weekly,login_frequency_weekly,avg_session_duration_min,video_watch_time_min,assignments_submitted,forum_posts,quiz_attempts,avg_quiz_score,attendance_rate,engagement_score,final_grade,dropout
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000
mean,25000.500000,33.539960,49.996111,10.009115,7.498780,40.044473,299.748579,4.486120,6.985980,4.003100,70.018199,0.700335,6.199321,36.854200,0.32412
std,14433.901067,9.188219,14.992648,4.000621,4.026195,14.966684,119.331233,2.872367,4.325459,1.998742,15.057111,0.173304,1.510398,9.012627,0.46805
min,1.000000,18.000000,-7.300000,-5.790000,1.000000,-19.874917,-237.960893,0.000000,0.000000,1.000000,1.940000,0.400000,-0.353095,-0.173269,0.00000
25%,12500.750000,26.000000,39.920000,7.310000,4.000000,29.986016,219.140815,2.000000,3.000000,2.000000,59.850000,0.550000,5.174603,30.765320,0.00000
50%,25000.500000,34.000000,50.050000,9.995000,8.000000,40.078174,299.620686,4.000000,7.000000,4.000000,70.000000,0.700000,6.200308,36.846286,0.00000
75%,37500.250000,41.000000,60.090000,12.680000,11.000000,50.159928,380.161206,7.000000,11.000000,6.000000,80.130000,0.850000,7.216701,42.936420,1.00000
max,50000.000000,49.000000,111.170000,25.540000,14.000000,108.765278,778.595742,9.000000,14.000000,7.000000,137.490000,1.000000,12.620085,73.717902,1.00000

Drop irrelevent **column**

In [ ]:
(df.drop("student_id", axis=1, inplace=True))

In [ ]:
df.columns

Index(['age', 'gender', 'country', 'device_type', 'internet_speed_mbps',
       'study_hours_weekly', 'login_frequency_weekly',
       'avg_session_duration_min', 'video_watch_time_min',
       'assignments_submitted', 'forum_posts', 'quiz_attempts',
       'avg_quiz_score', 'attendance_rate', 'engagement_score', 'final_grade',
       'dropout'],
      dtype='object')

In [ ]:
df.shape

(50000, 17)

In [ ]:
df.dtypes

age                           int64
gender                       object
country                      object
device_type                  object
internet_speed_mbps         float64
study_hours_weekly          float64
login_frequency_weekly        int64
avg_session_duration_min    float64
video_watch_time_min        float64
assignments_submitted         int64
forum_posts                   int64
quiz_attempts                 int64
avg_quiz_score              float64
attendance_rate             float64
engagement_score            float64
final_grade                 float64
dropout                       int64
dtype: object

In [ ]:
cat_cols = [col for col in df.columns if df[col].dtype == "object" ]

In [ ]:
num_cols = [col for col in df.columns if df[col].dtype != "object"]

In [ ]:
cat_cols

['gender', 'country', 'device_type']

In [ ]:
num_cols

['age',
 'internet_speed_mbps',
 'study_hours_weekly',
 'login_frequency_weekly',
 'avg_session_duration_min',
 'video_watch_time_min',
 'assignments_submitted',
 'forum_posts',
 'quiz_attempts',
 'avg_quiz_score',
 'attendance_rate',
 'engagement_score',
 'final_grade',
 'dropout']

In [ ]:
df.shape

(50000, 17)

In [ ]:
df.info

<bound method DataFrame.info of        age  gender    country device_type  internet_speed_mbps  \
0       24  Female        USA      Laptop                44.70
1       37  Female    Germany      Tablet                61.10
2       46  Female  Australia      Tablet                43.10
3       32    Male      India      Tablet                26.99
4       28    Male      India      Laptop                52.28
...    ...     ...        ...         ...                  ...
49995   41    Male     Canada      Laptop                72.05
49996   41  Female        USA      Laptop                49.61
49997   28    Male        USA      Mobile                65.99
49998   19  Female  Australia      Mobile                44.48
49999   36  Female    Germany      Tablet                41.16

       study_hours_weekly  login_frequency_weekly  avg_session_duration_min  \
0                   15.92                      10                 40.052752
1                    6.37                       8                 32.442671
2                    6.64                       7                 43.614509
3                   10.91                       5                 30.697263
4                    7.41                       6                 47.402999
...                   ...                     ...                       ...
49995               16.67                      11                 29.357895
49996               10.89                       5                 46.521225
49997               13.02                      11                 25.405865
49998               10.00                      10                 53.393459
49999                5.70                      13                 42.648018

       video_watch_time_min  assignments_submitted  forum_posts  \
0                294.099759                      3            4
1                400.397658                      7           14
2                190.239738                      1           14
3                370.451629                      3            1
4                151.341296                      4            4
...                     ...                    ...          ...
49995            317.570722                      4           13
49996            378.638038                      5            4
49997            358.872387                      3            7
49998            597.282683                      5            1
49999            310.477185                      0           10

       quiz_attempts  avg_quiz_score  attendance_rate  engagement_score  \
0                  6           46.69             0.93          8.046499
1                  5           62.65             0.59          6.312988
2                  5           58.42             0.43          4.143199
3                  2           61.21             0.65          6.125258
4                  6           74.92             0.55          4.979706
...              ...             ...              ...               ...
49995              1           49.05             0.47          7.588854
49996              1           64.51             0.73          6.360190
49997              1           97.90             0.60          6.500362
49998              6           73.26             0.55          8.186413
49999              6           80.46             0.95          4.462386

       final_grade  dropout
0        22.447641        0
1        39.749905        1
2        31.061688        1
3        41.300634        0
4        39.148998        1
...            ...      ...
49995    23.339360        1
49996    41.131751        0
49997    54.854903        0
49998    39.917221        1
49999    37.596538        0

[50000 rows x 17 columns]>

In [ ]:
df.describe()

,age,internet_speed_mbps,study_hours_weekly,login_frequency_weekly,avg_session_duration_min,video_watch_time_min,assignments_submitted,forum_posts,quiz_attempts,avg_quiz_score,attendance_rate,engagement_score,final_grade,dropout
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000
mean,33.539960,49.996111,10.009115,7.498780,40.044473,299.748579,4.486120,6.985980,4.003100,70.018199,0.700335,6.199321,36.854200,0.32412
std,9.188219,14.992648,4.000621,4.026195,14.966684,119.331233,2.872367,4.325459,1.998742,15.057111,0.173304,1.510398,9.012627,0.46805
min,18.000000,-7.300000,-5.790000,1.000000,-19.874917,-237.960893,0.000000,0.000000,1.000000,1.940000,0.400000,-0.353095,-0.173269,0.00000
25%,26.000000,39.920000,7.310000,4.000000,29.986016,219.140815,2.000000,3.000000,2.000000,59.850000,0.550000,5.174603,30.765320,0.00000
50%,34.000000,50.050000,9.995000,8.000000,40.078174,299.620686,4.000000,7.000000,4.000000,70.000000,0.700000,6.200308,36.846286,0.00000
75%,41.000000,60.090000,12.680000,11.000000,50.159928,380.161206,7.000000,11.000000,6.000000,80.130000,0.850000,7.216701,42.936420,1.00000
max,49.000000,111.170000,25.540000,14.000000,108.765278,778.595742,9.000000,14.000000,7.000000,137.490000,1.000000,12.620085,73.717902,1.00000